// Auto-generated by env-checker-strict
// ⚠️ Do not modify manually


/**
 * Always throw error if sensitive environment variable
 * not found, to detect issues immediately after boot.
 * Make sure to run `npx env-checker-strict` to update
 * this list if new env vars are added.
 */


/**
 * List of required environment variables.
 * Used for strict validation and reference.
 */
const ENV_LIST = [
  'ANOTHER'
];

/**
 * Access all environment variables with autocomplete and type safety support.
 * @typedef {Object} ENVS
 * @property {string} ANOTHER
 */

/** @type {ENVS} */
const ENVS = {
  ANOTHER: process.env.ANOTHER
};

/**
 * Throws an error if any required environment variable is missing.
 */
const checkEnvAndThrowError = () => {
  for (const env of ENV_LIST) {
    if (!process.env[env]) {
      const message =
        `[ENV ERROR] Missing required environment variable: ${env}\n` +
        `➡️  Make sure '${env}' is defined in your .env file.\n` +
        `📄 Location: ${__filename}`;

      console.error(message);
      throw new Error(message);
    }
  }
};

module.exports = { checkEnvAndThrowError, ENVS };